name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: [ llm, service ]  

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev default-libmysqlclient-dev build-essential pkg-config

      - name: Instalar pip
        run: |
          curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          python3 -m pip install --upgrade pip


      # 4Instalar dependencias del proyecto
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django

      # Ejecutar migraciones
      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      # Ejecutar tests con salida JUnit XML
      - name: Run Django tests
        run: |
          mkdir -p test-results
          pytest Controller/PreferenciasController/tests.py Controller/RecomendacionController/tests.py --ds=LLMService.settings --junitxml=test-results/junit.xml --maxfail=5 --disable-warnings -v

      # Publicar resumen visual bonito
      - name: ðŸ“Š Publish Pytest Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: "test-results/junit.xml"
          include_passed: true
          check_name: "IntegraciÃ³n ðŸ”§"
        if: always()
